"use client"

import { AlertTriangle, Check, Key, Link2, Shield, X } from "lucide-react"

function PlatformAccountCard() {
  return (
    <div
      className="rounded-2xl overflow-hidden relative"
      style={{
        background:
          "linear-gradient(145deg, rgba(30,12,12,1) 0%, rgba(20,8,8,1) 100%)",
        border: "1px solid rgba(239,68,68,0.2)",
      }}
    >
      <div
        className="h-9 flex items-center px-3.5 gap-1.5"
        style={{
          background: "rgba(255,255,255,0.03)",
          borderBottom: "1px solid rgba(255,255,255,0.05)",
        }}
      >
        <div
          className="w-2 h-2 rounded-full"
          style={{ background: "rgba(239,68,68,0.5)" }}
        />
        <div
          className="w-2 h-2 rounded-full"
          style={{ background: "rgba(251,191,36,0.5)" }}
        />
        <div
          className="w-2 h-2 rounded-full"
          style={{ background: "rgba(34,197,94,0.5)" }}
        />
      </div>

      <div className="p-5">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-9 h-9 rounded-full bg-red-500/20 flex items-center justify-center">
            <AlertTriangle className="w-4 h-4 text-red-400" />
          </div>
          <div>
            <p className="text-sm font-semibold text-white">Platform Account</p>
            <p className="text-xs text-white/40">The fragile identity</p>
          </div>
        </div>

        <div className="space-y-3 mb-5">
          <div className="flex items-center gap-2.5 text-sm text-white/50">
            <X className="w-4 h-4 text-red-400/70 flex-shrink-0" />
            <span>Issued by the platform</span>
          </div>
          <div className="flex items-center gap-2.5 text-sm text-white/50">
            <X className="w-4 h-4 text-red-400/70 flex-shrink-0" />
            <span>Can be revoked at any time</span>
          </div>
          <div className="flex items-center gap-2.5 text-sm text-white/50">
            <X className="w-4 h-4 text-red-400/70 flex-shrink-0" />
            <span>Lost if platform shuts down</span>
          </div>
          <div className="flex items-center gap-2.5 text-sm text-white/50">
            <X className="w-4 h-4 text-red-400/70 flex-shrink-0" />
            <span>Cannot be transferred</span>
          </div>
        </div>

        <div className="bg-red-500/10 rounded-lg p-3 border border-red-500/20">
          <p className="text-xs text-red-300/80 leading-relaxed">
            Your username, followers, reputation — all borrowed, never owned.
          </p>
        </div>
      </div>
    </div>
  )
}

function SelfSovereignCard() {
  return (
    <div
      className="rounded-2xl overflow-hidden relative"
      style={{
        background:
          "linear-gradient(145deg, rgba(12,30,20,1) 0%, rgba(8,20,14,1) 100%)",
        border: "1px solid rgba(16,185,129,0.2)",
      }}
    >
      <div
        className="h-9 flex items-center px-3.5 gap-1.5"
        style={{
          background: "rgba(255,255,255,0.03)",
          borderBottom: "1px solid rgba(255,255,255,0.05)",
        }}
      >
        <div
          className="w-2 h-2 rounded-full"
          style={{ background: "rgba(239,68,68,0.5)" }}
        />
        <div
          className="w-2 h-2 rounded-full"
          style={{ background: "rgba(251,191,36,0.5)" }}
        />
        <div
          className="w-2 h-2 rounded-full"
          style={{ background: "rgba(34,197,94,0.5)" }}
        />
      </div>

      <div className="p-5">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-9 h-9 rounded-full bg-emerald-500/20 flex items-center justify-center">
            <Shield className="w-4 h-4 text-emerald-400" />
          </div>
          <div>
            <p className="text-sm font-semibold text-white">
              Self-Sovereign Identity
            </p>
            <p className="text-xs text-white/40">The robust identity</p>
          </div>
        </div>

        <div className="space-y-3 mb-5">
          <div className="flex items-center gap-2.5 text-sm text-white/50">
            <Check className="w-4 h-4 text-emerald-400/70 flex-shrink-0" />
            <span>Generated by you, owned by you</span>
          </div>
          <div className="flex items-center gap-2.5 text-sm text-white/50">
            <Check className="w-4 h-4 text-emerald-400/70 flex-shrink-0" />
            <span>Impossible to revoke</span>
          </div>
          <div className="flex items-center gap-2.5 text-sm text-white/50">
            <Check className="w-4 h-4 text-emerald-400/70 flex-shrink-0" />
            <span>Works across all platforms</span>
          </div>
          <div className="flex items-center gap-2.5 text-sm text-white/50">
            <Check className="w-4 h-4 text-emerald-400/70 flex-shrink-0" />
            <span>Fully portable & transferable</span>
          </div>
        </div>

        <div className="bg-emerald-500/10 rounded-lg p-3 border border-emerald-500/20">
          <p className="text-xs text-emerald-300/80 leading-relaxed">
            Your identity exists independently. No platform can take it away.
          </p>
        </div>
      </div>
    </div>
  )
}

function IdentityFeatureCard({ icon: Icon, title, description }) {
  return (
    <div className="bg-dark-surface/50 rounded-xl p-5 border border-white/5">
      <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center mb-3">
        <Icon className="w-5 h-5 text-primary" />
      </div>
      <h4 className="text-sm font-semibold text-white mb-1.5">{title}</h4>
      <p className="text-xs text-white/50 leading-relaxed">{description}</p>
    </div>
  )
}

export function IdentitySection() {
  return (
    <section id="identity" className="landing-section bg-dark-surface/30">
      <div className="container-custom">
        <p className="section-label">Foundation</p>
        <h2 className="landing-heading mb-4">Decentralized Identity</h2>
        <p className="max-w-2xl text-dark-muted text-base leading-relaxed mb-12">
          Your identity on epress is your Ethereum address — a cryptographic key
          pair you generate yourself. No platform issued it. No platform can
          revoke it. It is mathematically yours.
        </p>

        <div className="max-w-3xl mx-auto mb-16 grid grid-cols-1 sm:grid-cols-2 gap-5">
          <PlatformAccountCard />
          <SelfSovereignCard />
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          <IdentityFeatureCard
            icon={Key}
            title="Cryptographic Ownership"
            description="Your private key never leaves your device. You sign, you prove, you control."
          />
          <IdentityFeatureCard
            icon={Link2}
            title="Universal Portability"
            description="Take your identity to any EWP-compatible platform. Your reputation travels with you."
          />
          <IdentityFeatureCard
            icon={Shield}
            title="Censorship Resistant"
            description="No central authority can suspend or delete your account. Your voice cannot be silenced."
          />
        </div>
      </div>
    </section>
  )
}
